"""Initial schema - creates all platform tables from current model metadata.

Revision ID: 0001
Revises:
Create Date: 2026-06-12

This bootstrap migration materialises the full model metadata. Subsequent
schema changes must be added as individual autogenerated revisions
(`alembic revision --autogenerate -m "..."`).
"""
from typing import Sequence, Union

from alembic import op

from app.core.database import Base
import app.models  # noqa: F401  register all models on Base.metadata

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
